package com.finance.enums;
 
public enum RoleType {
 
    ROLE_CITIZEN,
    ROLE_BUSINESS,
 
    ROLE_FINANCIAL_OFFICER,
    ROLE_PROGRAM_MANAGER,
 
    ROLE_COMPLIANCE_OFFICER,
    ROLE_GOVERNMENT_AUDITOR,
 
    ROLE_ADMIN
}