spring.application.name=config_server
server.port=8760
spring.cloud.config.server.git.uri=https://github.com/himanshu02525/config-server-repo.git
spring.cloud.config.server.git.skip-ssl-validation=true

#========================================================================
#please do not change anything in this file , if you want any property that
#is common so you can tell TL to add in repository
#========================================================================
